clone_folder: C:\VSTS

image: WMF 5

install:
  - ps: |
      Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
      Install-Module -Name Pester -Force -Scope CurrentUser

      # Install Nuget.exe to enable package creation
      $nugetExePath = Join-Path -Path $ENV:APPVEYOR_BUILD_FOLDER `
                                -ChildPath 'nuget.exe'
      $Uri = 'https://dist.nuget.org/win-x86-commandline/v3.4.4/NuGet.exe'
      Invoke-WebRequest -Uri $Uri -OutFile $nugetExePath

version: 1.0.{build}

build_script:
- ps: .\ci\New-ModuleManifest.ps1

test_script:
- ps: .\ci\Invoke-Tests.ps1

deploy_script:
- ps: .\ci\Publish-Module.ps1

environment:
  ApiKey:
    secure: jv+jb1IJtjQxAxQigSve12KwVeuu7evZk7Ot5PKapLebDyl2LHsQGcqZFQ8VeDxV
  VSTSPoshToken:
    secure: FynjMo+abZRZQv1RB0UnKzORp7YFmF9+ey17ezNxQ1abYcPzVhU+q4p/bbWA2xmwfyxVFg0xMGDssU6DhW4IJA==
  VSTSPoshUserName:
    secure: edlf8+6ClMjqoBuBweBkxQ==
  VSTSPoshAccount:
    secure: edlf8+6ClMjqoBuBweBkxQ==
