clone_folder: C:\VSTS

image: WMF 5

install:
  - cinst pester

version: 1.0.{build}
build_script:
- ps: New-ModuleManifest -ModuleVersion $ENV:APPVEYOR_BUILD_VERSION -Path .\VSTS.psd1 -Author 'Adam Driscoll' -Company 'Concurrency, Inc' -Description 'Visual Studio Team Services PowerShell Integration' -RootModule '.\VSTS.psm1' 

test_script:
  - ps: $res = Invoke-Pester -Path ".\" -OutputFormat NUnitXml -OutputFile TestsResults.xml -PassThru
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestsResults.xml))
  - ps: if ($res.FailedCount -gt 0) { throw "$($res.FailedCount) tests failed."}
  
deploy_script:
- ps: Install-PackageProvider -Name NuGet -Force 
- ps: if ($env:APPVEYOR_REPO_BRANCH -eq 'main') { Publish-Module -NuGetApiKey $env:ApiKey -Path C:\VSTS } 

environment:
  ApiKey:
    secure: jv+jb1IJtjQxAxQigSve12KwVeuu7evZk7Ot5PKapLebDyl2LHsQGcqZFQ8VeDxV